# Generated by Django 3.0 on 2021-08-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=5)),
                ('image_name', models.ImageField(blank=True, default='pictures/default/default.png', upload_to='pictures/')),
                ('activate', models.BooleanField(default=False)),
                ('file_name', models.FileField(upload_to='csvs')),
                ('subjects', models.ManyToManyField(to='teacherProfile.Subject')),
            ],
        ),
    ]
