# Generated by Django 3.0 on 2021-08-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='file_name',
        ),
    ]
