# Generated by Django 3.0 on 2021-08-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='activate',
        ),
        migrations.AddField(
            model_name='csv',
            name='activated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
